@startuml

title __ECOMMERCE's Class Diagram__\n

  namespace com.lestscode.ecommerce {
    class com.lestscode.ecommerce.EcommerceApplication {
    }
  }
  

  namespace com.lestscode.ecommerce {
    namespace controllers {
      class com.lestscode.ecommerce.controllers.CustomerController {
      }
    }
  }
  

  namespace com.lestscode.ecommerce {
    namespace exceptions {
      class com.lestscode.ecommerce.exceptions.CpfInvalidoException {
      }
    }
  }
  

  namespace com.lestscode.ecommerce {
    namespace exceptions {
      class com.lestscode.ecommerce.exceptions.PhoneException {
      }
    }
  }
  

  namespace com.lestscode.ecommerce {
    namespace models {
      interface com.lestscode.ecommerce.models.Validacao {
      }
    }
  }
  

  namespace com.lestscode.ecommerce {
    namespace models {
      namespace customer {
        class com.lestscode.ecommerce.models.customer.CPF {
        }
      }
    }
  }
  

  namespace com.lestscode.ecommerce {
    namespace models {
      namespace customer {
        class com.lestscode.ecommerce.models.customer.Customer {
        }
      }
    }
  }
  

  namespace com.lestscode.ecommerce {
    namespace models {
      namespace customer {
        class com.lestscode.ecommerce.models.customer.CustomerAddress {
        }
      }
    }
  }
  

  namespace com.lestscode.ecommerce {
    namespace models {
      namespace customer {
        class com.lestscode.ecommerce.models.customer.Email {
        }
      }
    }
  }
  

  namespace com.lestscode.ecommerce {
    namespace models {
      namespace customer {
        class com.lestscode.ecommerce.models.customer.Phone {
        }
      }
    }
  }
  

  namespace com.lestscode.ecommerce {
    namespace models {
      namespace dto {
        class com.lestscode.ecommerce.models.dto.CustomerDto {
        }
      }
    }
  }
  

  namespace com.lestscode.ecommerce {
    namespace models {
      namespace order {
        class com.lestscode.ecommerce.models.order.Order {
        }
      }
    }
  }
  

  namespace com.lestscode.ecommerce {
    namespace models {
      namespace order {
        class com.lestscode.ecommerce.models.order.OrderItem {
        }
      }
    }
  }
  

  namespace com.lestscode.ecommerce {
    namespace models {
      namespace order {
        enum OrderStatus {
        }
      }
    }
  }
  

  namespace com.lestscode.ecommerce {
    namespace models {
      namespace product {
        class com.lestscode.ecommerce.models.product.Product {
        }
      }
    }
  }
  

  namespace com.lestscode.ecommerce {
    namespace repositories {
      interface com.lestscode.ecommerce.repositories.CustomerRepository {
      }
    }
  }
  

  namespace com.lestscode.ecommerce {
    namespace services {
      class com.lestscode.ecommerce.services.CustomerServices {
      }
    }
  }
  

  namespace com.lestscode.ecommerce {
    namespace services {
      namespace interfaces {
        interface com.lestscode.ecommerce.services.interfaces.ICustomeService {
        }
      }
    }
  }
  

  com.lestscode.ecommerce.controllers.CustomerController o-- com.lestscode.ecommerce.services.interfaces.ICustomeService : customeService
  com.lestscode.ecommerce.models.customer.CPF .up.|> com.lestscode.ecommerce.models.Validacao
  com.lestscode.ecommerce.models.customer.Customer o-- com.lestscode.ecommerce.models.customer.CustomerAddress : address
  com.lestscode.ecommerce.models.customer.Customer o-- com.lestscode.ecommerce.models.customer.CPF : cpf
  com.lestscode.ecommerce.models.customer.Customer o-- com.lestscode.ecommerce.models.customer.Email : email
  com.lestscode.ecommerce.models.customer.Customer o-- com.lestscode.ecommerce.models.customer.Phone : phone
  com.lestscode.ecommerce.models.customer.Email .up.|> com.lestscode.ecommerce.models.Validacao
  com.lestscode.ecommerce.models.customer.Phone .up.|> com.lestscode.ecommerce.models.Validacao
  com.lestscode.ecommerce.models.order.Order o-- com.lestscode.ecommerce.models.customer.Customer : customer
  com.lestscode.ecommerce.models.order.Order o-- com.lestscode.ecommerce.models.order.OrderStatus : status
  com.lestscode.ecommerce.models.order.OrderItem o-- com.lestscode.ecommerce.models.product.Product : product
  com.lestscode.ecommerce.services.CustomerServices .up.|> com.lestscode.ecommerce.services.interfaces.ICustomeService
  com.lestscode.ecommerce.services.CustomerServices o-- com.lestscode.ecommerce.repositories.CustomerRepository : customerRepository


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
