@startuml

title __CUSTOMER's Class Diagram__\n

  namespace com.lestscode.ecommerce {
    namespace models {
      namespace customer {
        class com.lestscode.ecommerce.models.customer.CPF {
            - cpfNumber : String
            + CPF()
            + getCpf()
            + validar()
        }
      }
    }
  }
  

  namespace com.lestscode.ecommerce {
    namespace models {
      namespace customer {
        class com.lestscode.ecommerce.models.customer.Customer {
            - id : Long
            - name : String
            - password : String
            + Customer()
            + Customer()
            + getAddress()
            + getCpf()
            + getEmail()
            + getName()
            + getPassword()
            + getPhone()
            + setAddress()
            + setCpf()
            + setEmail()
            + setId()
            + setName()
            + setPassword()
            + setPhone()
        }
      }
    }
  }
  

  namespace com.lestscode.ecommerce {
    namespace models {
      namespace customer {
        class com.lestscode.ecommerce.models.customer.CustomerAddress {
            - bairro : String
            - cep : String
            - cidade : String
            - estado : String
            - logradouro : String
            - numero : String
            + CustomerAddress()
            + getEndereco()
        }
      }
    }
  }
  

  namespace com.lestscode.ecommerce {
    namespace models {
      namespace customer {
        class com.lestscode.ecommerce.models.customer.Email {
            - email : String
            + Email()
            + getEmail()
            + validar()
        }
      }
    }
  }
  

  namespace com.lestscode.ecommerce {
    namespace models {
      namespace customer {
        class com.lestscode.ecommerce.models.customer.Phone {
            + ddd : String
            + numero : String
            + Phone()
            + getTelefone()
            + validar()
        }
      }
    }
  }
  

  com.lestscode.ecommerce.models.customer.CPF .up.|> com.lestscode.ecommerce.models.Validacao
  com.lestscode.ecommerce.models.customer.Customer o-- com.lestscode.ecommerce.models.customer.CustomerAddress : address
  com.lestscode.ecommerce.models.customer.Customer o-- com.lestscode.ecommerce.models.customer.CPF : cpf
  com.lestscode.ecommerce.models.customer.Customer o-- com.lestscode.ecommerce.models.customer.Email : email
  com.lestscode.ecommerce.models.customer.Customer o-- com.lestscode.ecommerce.models.customer.Phone : phone
  com.lestscode.ecommerce.models.customer.Email .up.|> com.lestscode.ecommerce.models.Validacao
  com.lestscode.ecommerce.models.customer.Phone .up.|> com.lestscode.ecommerce.models.Validacao


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
